# Generated by Django 5.0.6 on 2024-05-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_product_product_id_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'pending'), ('complete', 'complete'), ('cancelled', 'cancelled')], default='pending', max_length=50, null=True),
        ),
    ]
